# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e0bd74ebc3fc65ca721207c5b4d6af107687fe4baf7f8f97debc51b3cfe58d0ff8bb35fd303e856eacfb82057c61c63bcadb12ecfc82e709ea67adb63312dd1

test:
  secret_key_base: 679b8b9d79b85ba9671a5a5d1836c750abb9d9233d2034fd7318532cbaee1cf4da9e1813d2737c4ff947f572e00e67255a478efc8ab21b76d409cd10355ef6fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
